#!/usr/bin/env python2

import sys, os, getopt, glob, codecs, fnmatch
scriptPath = os.path.realpath(os.path.dirname(sys.argv[0]))
sys.path.append(scriptPath + os.sep + 'lib')
from tiddlywiki import TiddlyWiki


def usage():
   print 'usage: braid [-a author] [-t target] [-m mergefile] [-o outputfile] [-l file list] [-d directory] [-f filetype] [-p proofcopy] [(-b -r)-e errorfile] source1 [source2..]'


def main (argv):

   # defaults

   author = 'braid'
   target = 'sugarcube'
   merge = ''
   output = ''
   rtfOutput = ''
   fileList = ''
   directory = ''
   twineFiletype = '.tw'
   errorfile = ''
   brokenLink = False
   showReverse = False

   # read command line switches

   try:
      opts, args = getopt.getopt(argv, 'a:m:t:o:l:d:f:p:bre:', ['author=', 'merge=', \
         'target=', 'output=', 'list=', 'directory=', 'filetype=', 'proofcopy=', \
         'brokenlink', 'revpassage', 'errorfile='])
   except getopt.GetoptError:
      usage()
      sys.exit(2)

   for opt, arg in opts:
      if (opt in ('-a', '--author')):
         author = arg
      elif (opt in ('-m', '--merge')):
         merge = arg
      elif (opt in ('-t', '--target')):
         target = arg
      elif (opt in ('-o', '--output')):
         output = arg
      elif (opt in ('-l', '--list')):
         fileList = arg
      elif (opt in ('-d', '--directory')):
         directory = arg
      elif (opt in ('-f', '--filetype')):
         twineFiletype = arg
      elif (opt in ('-p', '--proofcopy')):
         rtfOutput = arg
      elif (opt in ('-e', '--errorfile')):
         errorfile = arg
      elif (opt in ('-b', '--brokenlink')):
         brokenLink = True
      elif (opt in ('-r', '--revpassage')):
         showReverse = True

   # construct a TW object

   tw = TiddlyWiki(author)

   # read in a file to be merged

   if merge != '':
      try:
         mergeFile = codecs.open(merge, 'r', 'utf-8-sig', 'strict')
         fileString = mergeFile.read()
      except UnicodeDecodeError:
         try:
            mergeFile = codecs.open(merge, 'r', 'utf16', 'strict')
            fileString = mergeFile.read()
         except:
            mergeFile = open(merge, 'rb')
            fileString = source.read()
      mergeFile.close()
      tw.addHtml(fileString)

   # read source files		

   sources = []

   # Read File List, if present
   if fileList != '':
      try:
         fileListFile = codecs.open(fileList, 'r', 'utf-8-sig', 'strict')
      except UnicodeDecodeError:
         try:
            fileListFile = codecs.open(fileList, 'r', 'utf16', 'strict')
         except:
            fileListFile = open(fileList, 'rb')
      for fileName in fileListFile:
         for file in glob.glob(fileName.strip()):
            sources.append(file)
      fileListFile.close()

   # Read files from command line
   for arg in args:
      for file in glob.glob(arg):
         sources.append(file)

   # Recurse through directory, if specified
   for root, dirnames, filenames in os.walk(directory):
      for filename in fnmatch.filter(filenames, '*' + twineFiletype):
         sources.append(os.path.join(root, filename))

   if len(sources) == 0:
      print 'braid: no source files specified\n'
      sys.exit(2)	
   
   # Load Twee Files
   for source in sources:
      tw.addTweeFromFilename(source)

   # Output RTF proofing file if requested
   if rtfOutput != '':
      rtfOutputFile = open(rtfOutput, 'w')
      rtfOutputFile.write(tw.toRtf().encode('utf-8'))
      rtfOutputFile.close()

   # Either Output to a file if requested, or to standard output
   if output != '':
      outputFile = open(output, 'w')
      outputFile.write(tw.toHtml(scriptPath, target).encode('utf-8'))
      outputFile.close()
   else:
      print tw.toHtml(scriptPath, target)

   # Outputs a broken link/orphan list if requested
   if errorfile != '':
      broken, orphans, passagelinks = tw.getLinks()
      errorFile = open(errorfile, 'w')
      if brokenLink:
         errorFile.write("Broken Links:\n")
         for passage in broken:
            errorFile.write(" - " + passage + "\n")
            for link in broken[passage]:
               errorFile.write("    + " + link + "\n")
         errorFile.write("Orphaned Passages:\n")
         for passage in orphans:
            errorFile.write(" - " + passage + "\n")
      if showReverse:
         errorFile.write("Links to Passages:\n")
         for passage in passagelinks.keys():
            errorFile.write(" - " + passage + ": " + str(len(passagelinks[passage])) + " links to passage\n")
            for linkto in passagelinks[passage]:
               errorFile.write("     + " + linkto + "\n")
      errorFile.close()

if __name__ == '__main__':
   main(sys.argv[1:])
